// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aeab2fda-0e82-48f7-8b13-570a45131986",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_to1RXpSg7",
    "aws_user_pools_web_client_id": "33c73u1beg8vv32jikfnjo87v7",
    "aws_content_delivery_bucket": "website-20180906062043--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://website-20180906062043--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
